# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cf9c72fde3e3796b07de66746adfd7d3c3878aaf269f2df275c480be6200ee72e154c8b628d70a8b32f18e4d174c9a9b5aae57bacf73367ee11307b246941d8

test:
  secret_key_base: bdfe26d6da021219cbb77e548f347ffdfb09d5f269b6351eeccc9afc724e0c78ec8cfafbbe2a6faac66556e57c75bf177265f78fd38de4a529868af74ecc2bc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
